//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenDataDBBuilder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenDataDBBuilder.Properties.Resources_en-US", typeof(Resources_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New database.
        /// </summary>
        internal static string AddDBForm {
            get {
                return ResourceManager.GetString("AddDBForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string btnOKDB {
            get {
                return ResourceManager.GetString("btnOKDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose File.
        /// </summary>
        internal static string btnOpenFile {
            get {
                return ResourceManager.GetString("btnOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string btnTest {
            get {
                return ResourceManager.GetString("btnTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Columns.
        /// </summary>
        internal static string ChangeColumnForm {
            get {
                return ResourceManager.GetString("ChangeColumnForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Tables.
        /// </summary>
        internal static string CreateTablesForm {
            get {
                return ResourceManager.GetString("CreateTablesForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit {0} Connection.
        /// </summary>
        internal static string EditDBConnectionForm {
            get {
                return ResourceManager.GetString("EditDBConnectionForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: .
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete FK for {0} column.
        /// </summary>
        internal static string errorMsgFK {
            get {
                return ResourceManager.GetString("errorMsgFK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info: .
        /// </summary>
        internal static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        internal static string lblColumnText {
            get {
                return ResourceManager.GetString("lblColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databases:.
        /// </summary>
        internal static string lblDataBases {
            get {
                return ResourceManager.GetString("lblDataBases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database: .
        /// </summary>
        internal static string lblDB {
            get {
                return ResourceManager.GetString("lblDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language: .
        /// </summary>
        internal static string lblLanguage {
            get {
                return ResourceManager.GetString("lblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        internal static string lblPort {
            get {
                return ResourceManager.GetString("lblPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server:.
        /// </summary>
        internal static string lblServer {
            get {
                return ResourceManager.GetString("lblServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables:.
        /// </summary>
        internal static string lblTables {
            get {
                return ResourceManager.GetString("lblTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string lblTypeText {
            get {
                return ResourceManager.GetString("lblTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User:.
        /// </summary>
        internal static string lblUser {
            get {
                return ResourceManager.GetString("lblUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Database selected!.
        /// </summary>
        internal static string noDBMsg {
            get {
                return ResourceManager.GetString("noDBMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No SQL to create tables!.
        /// </summary>
        internal static string noSQLMsg {
            get {
                return ResourceManager.GetString("noSQLMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file.
        /// </summary>
        internal static string openFileDialogTitleMsg {
            get {
                return ResourceManager.GetString("openFileDialogTitleMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Preview.
        /// </summary>
        internal static string SQLPreviewForm {
            get {
                return ResourceManager.GetString("SQLPreviewForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table .
        /// </summary>
        internal static string table {
            get {
                return ResourceManager.GetString("table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ODDB: Tables View.
        /// </summary>
        internal static string TablesForm {
            get {
                return ResourceManager.GetString("TablesForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed!.
        /// </summary>
        internal static string testFail {
            get {
                return ResourceManager.GetString("testFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfull connecion!.
        /// </summary>
        internal static string testSuccess {
            get {
                return ResourceManager.GetString("testSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string tsiCreate {
            get {
                return ResourceManager.GetString("tsiCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        internal static string tsiCreateDatabase {
            get {
                return ResourceManager.GetString("tsiCreateDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Columns.
        /// </summary>
        internal static string tsiEditColumns {
            get {
                return ResourceManager.GetString("tsiEditColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string tsiFile {
            get {
                return ResourceManager.GetString("tsiFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string tsiLanguage {
            get {
                return ResourceManager.GetString("tsiLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string tsiOpenFile {
            get {
                return ResourceManager.GetString("tsiOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string tsiOptions {
            get {
                return ResourceManager.GetString("tsiOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Preview.
        /// </summary>
        internal static string tsiPreviewSQL {
            get {
                return ResourceManager.GetString("tsiPreviewSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        internal static string tsiTables {
            get {
                return ResourceManager.GetString("tsiTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        internal static string tsiTablesCreate {
            get {
                return ResourceManager.GetString("tsiTablesCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Tables.
        /// </summary>
        internal static string tsiTablesEdit {
            get {
                return ResourceManager.GetString("tsiTablesEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating file.
        /// </summary>
        internal static string validatingXML {
            get {
                return ResourceManager.GetString("validatingXML", resourceCulture);
            }
        }
    }
}
