//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenDataDBBuilder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_pt_BR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_pt_BR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenDataDBBuilder.Properties.Resources_pt-BR", typeof(Resources_pt_BR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo banco de dados.
        /// </summary>
        internal static string AddDBForm {
            get {
                return ResourceManager.GetString("AddDBForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar.
        /// </summary>
        internal static string btnBackStep {
            get {
                return ResourceManager.GetString("btnBackStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizar.
        /// </summary>
        internal static string btnFinish {
            get {
                return ResourceManager.GetString("btnFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avançar.
        /// </summary>
        internal static string btnNextStep {
            get {
                return ResourceManager.GetString("btnNextStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string btnOK {
            get {
                return ResourceManager.GetString("btnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        internal static string btnOKDB {
            get {
                return ResourceManager.GetString("btnOKDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir.
        /// </summary>
        internal static string btnOpenFile {
            get {
                return ResourceManager.GetString("btnOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserir Valores.
        /// </summary>
        internal static string btnPreviewInsertValues {
            get {
                return ResourceManager.GetString("btnPreviewInsertValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        internal static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurar conexão.
        /// </summary>
        internal static string btnSetDbConnection {
            get {
                return ResourceManager.GetString("btnSetDbConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testar.
        /// </summary>
        internal static string btnTest {
            get {
                return ResourceManager.GetString("btnTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor default:.
        /// </summary>
        internal static string cbxDeafultValue {
            get {
                return ResourceManager.GetString("cbxDeafultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pular.
        /// </summary>
        internal static string cbxSkipText {
            get {
                return ResourceManager.GetString("cbxSkipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parar se houver erro.
        /// </summary>
        internal static string cbxStopOnError {
            get {
                return ResourceManager.GetString("cbxStopOnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Colunas.
        /// </summary>
        internal static string ChangeColumnForm {
            get {
                return ResourceManager.GetString("ChangeColumnForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edita nomes das tabelas.
        /// </summary>
        internal static string ChangeTablesForm {
            get {
                return ResourceManager.GetString("ChangeTablesForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Conexão {0}.
        /// </summary>
        internal static string EditDBConnectionForm {
            get {
                return ResourceManager.GetString("EditDBConnectionForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro: .
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete a FK da coluna {0}.
        /// </summary>
        internal static string errorMsgFK {
            get {
                return ResourceManager.GetString("errorMsgFK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executar Query.
        /// </summary>
        internal static string ExecuteSQLForm {
            get {
                return ResourceManager.GetString("ExecuteSQLForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info: .
        /// </summary>
        internal static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserir valores?.
        /// </summary>
        internal static string initialMessageInserting {
            get {
                return ResourceManager.GetString("initialMessageInserting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserir dados.
        /// </summary>
        internal static string InsertDataForm {
            get {
                return ResourceManager.GetString("InsertDataForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coluna.
        /// </summary>
        internal static string lblCollumnName {
            get {
                return ResourceManager.GetString("lblCollumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coluna.
        /// </summary>
        internal static string lblColumnText {
            get {
                return ResourceManager.GetString("lblColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banco de dados:.
        /// </summary>
        internal static string lblDatabase {
            get {
                return ResourceManager.GetString("lblDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bancos:.
        /// </summary>
        internal static string lblDataBases {
            get {
                return ResourceManager.GetString("lblDataBases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivo de dados:.
        /// </summary>
        internal static string lblDataFile {
            get {
                return ResourceManager.GetString("lblDataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * arquivo para extração dos dados.
        /// </summary>
        internal static string lblDataFileHelp {
            get {
                return ResourceManager.GetString("lblDataFileHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banco de Dados: .
        /// </summary>
        internal static string lblDB {
            get {
                return ResourceManager.GetString("lblDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma: .
        /// </summary>
        internal static string lblLanguage {
            get {
                return ResourceManager.GetString("lblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limite:.
        /// </summary>
        internal static string lblLimit {
            get {
                return ResourceManager.GetString("lblLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # de conexões.
        /// </summary>
        internal static string lblNofConn {
            get {
                return ResourceManager.GetString("lblNofConn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ação para erros.
        /// </summary>
        internal static string lblOnErrorAction {
            get {
                return ResourceManager.GetString("lblOnErrorAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha:.
        /// </summary>
        internal static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porta:.
        /// </summary>
        internal static string lblPort {
            get {
                return ResourceManager.GetString("lblPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servidor:.
        /// </summary>
        internal static string lblServer {
            get {
                return ResourceManager.GetString("lblServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabela ou coluna a ser criada.
        /// </summary>
        internal static string lblTableColumn {
            get {
                return ResourceManager.GetString("lblTableColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabelas:.
        /// </summary>
        internal static string lblTables {
            get {
                return ResourceManager.GetString("lblTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template:.
        /// </summary>
        internal static string lblTemplateFile {
            get {
                return ResourceManager.GetString("lblTemplateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * pula outras configurações.
        /// </summary>
        internal static string lblTemplateHelp {
            get {
                return ResourceManager.GetString("lblTemplateHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolha os arquivos.
        /// </summary>
        internal static string lblTextStepOne {
            get {
                return ResourceManager.GetString("lblTextStepOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defina a conexão.
        /// </summary>
        internal static string lblTextStepThree {
            get {
                return ResourceManager.GetString("lblTextStepThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolha o banco.
        /// </summary>
        internal static string lblTextStepTwo {
            get {
                return ResourceManager.GetString("lblTextStepTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        internal static string lblTypeText {
            get {
                return ResourceManager.GetString("lblTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banco selecionado.
        /// </summary>
        internal static string lblUsedDB {
            get {
                return ResourceManager.GetString("lblUsedDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário:.
        /// </summary>
        internal static string lblUser {
            get {
                return ResourceManager.GetString("lblUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivo de dados inválido.
        /// </summary>
        internal static string msgErrorInvalidDataFile {
            get {
                return ResourceManager.GetString("msgErrorInvalidDataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum arquivo de dados selecionado!.
        /// </summary>
        internal static string msgErrorNoDataFile {
            get {
                return ResourceManager.GetString("msgErrorNoDataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivo não suportado.
        /// </summary>
        internal static string msgInvalidExtension {
            get {
                return ResourceManager.GetString("msgInvalidExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O template tem configurações de conexão inválidas! Favor configurar sua conexão.
        /// </summary>
        internal static string msgInvalidTemplateConnection {
            get {
                return ResourceManager.GetString("msgInvalidTemplateConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O arquivo de template é inválido para o arquivo de dados selecionado!.
        /// </summary>
        internal static string msgInvalidTemplateDataFile {
            get {
                return ResourceManager.GetString("msgInvalidTemplateDataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comando SQL executado com sucesso!.
        /// </summary>
        internal static string msgSuccessExecuteSQL {
            get {
                return ResourceManager.GetString("msgSuccessExecuteSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum banco selecionado!.
        /// </summary>
        internal static string noDBMsg {
            get {
                return ResourceManager.GetString("noDBMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sem SQL para criação das tabelas!.
        /// </summary>
        internal static string noSQLMsg {
            get {
                return ResourceManager.GetString("noSQLMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um arquivo.
        /// </summary>
        internal static string openFileDialogTitleMsg {
            get {
                return ResourceManager.GetString("openFileDialogTitleMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserir valor default:.
        /// </summary>
        internal static string rbtnDefaultValueText {
            get {
                return ResourceManager.GetString("rbtnDefaultValueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pular registro.
        /// </summary>
        internal static string rbtnSkipLineText {
            get {
                return ResourceManager.GetString("rbtnSkipLineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao inserir linhas.
        /// </summary>
        internal static string retInsertRowsError {
            get {
                return ResourceManager.GetString("retInsertRowsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vizualização de SQL.
        /// </summary>
        internal static string SQLPreviewForm {
            get {
                return ResourceManager.GetString("SQLPreviewForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabela .
        /// </summary>
        internal static string table {
            get {
                return ResourceManager.GetString("table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ODDB: Visão de Tabelas.
        /// </summary>
        internal static string TablesForm {
            get {
                return ResourceManager.GetString("TablesForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha na{0}conexão!.
        /// </summary>
        internal static string testFail {
            get {
                return ResourceManager.GetString("testFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conexão{0}bem-sucedida!.
        /// </summary>
        internal static string testSuccess {
            get {
                return ResourceManager.GetString("testSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conexão.
        /// </summary>
        internal static string tsiConnection {
            get {
                return ResourceManager.GetString("tsiConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar.
        /// </summary>
        internal static string tsiCreate {
            get {
                return ResourceManager.GetString("tsiCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banco de Dados.
        /// </summary>
        internal static string tsiCreateDatabase {
            get {
                return ResourceManager.GetString("tsiCreateDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        internal static string tsiEdit {
            get {
                return ResourceManager.GetString("tsiEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colunas.
        /// </summary>
        internal static string tsiEditColumns {
            get {
                return ResourceManager.GetString("tsiEditColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivo.
        /// </summary>
        internal static string tsiFile {
            get {
                return ResourceManager.GetString("tsiFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserir.
        /// </summary>
        internal static string tsiInsert {
            get {
                return ResourceManager.GetString("tsiInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        internal static string tsiLanguage {
            get {
                return ResourceManager.GetString("tsiLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir.
        /// </summary>
        internal static string tsiOpenFile {
            get {
                return ResourceManager.GetString("tsiOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opções.
        /// </summary>
        internal static string tsiOptions {
            get {
                return ResourceManager.GetString("tsiOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vizualização de SQL.
        /// </summary>
        internal static string tsiPreviewSQL {
            get {
                return ResourceManager.GetString("tsiPreviewSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar Template.
        /// </summary>
        internal static string tsiSaveTemplate {
            get {
                return ResourceManager.GetString("tsiSaveTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabelas.
        /// </summary>
        internal static string tsiTablesCreate {
            get {
                return ResourceManager.GetString("tsiTablesCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabelas.
        /// </summary>
        internal static string tsiTablesEdit {
            get {
                return ResourceManager.GetString("tsiTablesEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validando arquivo.
        /// </summary>
        internal static string validatingXML {
            get {
                return ResourceManager.GetString("validatingXML", resourceCulture);
            }
        }
    }
}
